services:
  app:
    build:
      context: ./
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
