"""Add task_id to reviews table

Revision ID: 122df8c9b126
Revises: e364cdfa46b5
Create Date: 2025-05-09 13:33:37.786194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122df8c9b126'
down_revision: Union[str, None] = 'e364cdfa46b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Добавляем столбец как nullable
    op.add_column('reviews', sa.Column('task_id', sa.Integer(), nullable=True))
    # Заполняем значения (например, 0 или другое значение по умолчанию)
    op.execute("UPDATE reviews SET task_id = 0 WHERE task_id IS NULL")
    # Делаем столбец NOT NULL
    op.alter_column('reviews', 'task_id', nullable=False)
    # Добавляем внешний ключ
    op.create_foreign_key(None, 'reviews', 'tasks', ['task_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'task_id')
    # ### end Alembic commands ###